language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user -f ./udagram-api-user/Dockerfile .
  - docker tag udagram-api-user phuocht25292/udagram-api-user:v10

  - docker build -t udagram-api-feed -f ./udagram-api-feed/Dockerfile .
  - docker tag udagram-api-feed phuocht25292/udagram-api-feed:v10

  - docker build -t udagram-user -f ./udagram-frontend/Dockerfile .
  - docker tag udagram-frontend phuocht25292/udagram-frontend:v10

  - docker build -t udagram-reverseproxy -f ./udagram-reverseproxy/Dockerfile .
  - docker tag udagram-reverseproxy phuocht25292/udagram-reverseproxy:v10

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push phuocht25292/udagram-api-user:v10
  - docker push phuocht25292/udagram-api-feed:v10
  - docker push phuocht25292/udagram-frontend:v10
  - docker push phuocht25292/udagram-reverseproxy:v10